### ISSUE TITLE
We'd like to contribute a new class, but need the maintainer's opinion

### ISSUE THREAD

**Issue by scstarkey** [styleseek/honeybadger-java#3]
Greetings,
We're considering writing a class that uses the HoneyBadger class from inside of a Log4J appender. This requires us to have the log4j jar files available at compile-time. We see three options for making this happen:

1. Adding ivy to the existing build.xml,
2. Replacing the build.xml with a Maven pom.xml, or
3. Replacing the build.xml with a Gradle build.gradle file.

Which do you prefer?

Thanks!

**Comment by scstarkey** [comment]
FYI -- we made a simple gradle file and it looks like this:

https://github.com/opinionlab/honeybadger-java/blob/master/build.gradle

We'll happily conform to your preferences if that would help with accepting a pull request.

**Comment by page1** [comment]
Hi @scstarkey 
We are excited to see your pull. Send the gradle file over :)

**Comment by page1** [comment]
Looking over the fork history and spotted this possibly more developed version if your interested. It already has a gradle file.

https://github.com/dekobon/honeybadger-jvm-client-v2

**Comment by page1** [comment]
closed with pull #5
